### ISSUE TITLE
Add system/dynamic variables in template

### ISSUE THREAD

**Issue by Jany-M** [bendera/vscode-commit-message-editor#10]
Hello and thank you for the extension!

Would it possible to add a couple sys variables in the template?
`Eg. {current sys date - time}, {tot staged files}, {local pc name}`

The most pressing for me would be the time one (I would love to have it as a default commit msg whenever I don't want to manually write one), the others are just suggestions.
Would be great if easily clickable/selectable from the `Edit commit message` screen, but it's ok if it's just a list that we can copy/paste.

**Comment by bendera** [comment]
Hi Jany,

I'm glad you like my extension. Well... I could implement this feature, but to be honest I don't understand why do you need that. Every commit has a timestamp, so this information would be redundant in the commit message.

**Comment by Jany-M** [comment]
@bendera yes I'm aware of the timestamp, it's just a personal preference because I tend to focus on commit descriptions when working, rather than their dates and because often I don't want to have to write anything, so I just want some default text that's not completely meaningless like "minor edits" :)
What do you think about the other ones then? or even max 3 filename with most edits?
Something dynamic that I don't need to change each time, would be amazing!

**Comment by bendera** [comment]
Hi Jany,

I still don't want to add this feature to the extension but I would recommend an alternative method. :) There is an extension that can inject a timestamp to any opened editor. 
https://marketplace.visualstudio.com/items?itemName=jsynowiec.vscode-insertdatestring
My extension uses a different API, so you cannot use it with that, but you can set up VSCode as a default editor in GIT, instead of VI:
https://git-scm.com/book/en/v2/Appendix-C%3A-Git-Commands-Setup-and-Config
