### ISSUE TITLE
[feat] Provide a mono-space font in the editor form.

### ISSUE THREAD

**Issue by krzikalla** [bendera/vscode-commit-message-editor#31]
Is it possible to edit the commit message in a mono-space font?
If not, can we have an option to customize the font?

And if we are there: can we then have an option for a vertical marker 
line (e.g.at 72 chars)?

**Comment by bendera** [comment]
Not yet, but I have been planning this for a while. Or I might implement the same validator which exists in the VSCode. If this feature worked would you need the monospace thing?

![validator](https://user-images.githubusercontent.com/3748508/110353662-9b2e6e00-8037-11eb-8fc0-e5e1c71a2158.png)

**Comment by krzikalla** [comment]
It would help at least. However I also use intendations in my commit messages, which are easier to edit with monospaced fonts.

**Comment by DervishD** [comment]
Same here, monospaced fonts for commit messages are so hardcoded in my brain that for me this otherwise useful (and frankly, incredibly powerful) extension is unusable.

A length validator would be perfect for me, too. Optional or customizable, I suppose, as some people prefer their own line length for git commits.

Thanks a lot for the extension, BTW.

**Comment by bendera** [comment]
I'm going to implement that. Stay tuned.

**Comment by DervishD** [comment]
Sounds GREAT 💯 😄

**Comment by bendera** [comment]
Check the new version. ;)

**Comment by DervishD** [comment]
WONDERFUL!!!! Thanks a lot, really :))))) Works like a charm, BTW, I just tested it.

**Comment by krzikalla** [comment]
>  Works like a charm
You took the words right out of my mouth.
Great, change, thank you.
