### ISSUE TITLE
[bug] Message created for wrong repository

### ISSUE THREAD

**Issue by sattellite** [bendera/vscode-commit-message-editor#39]
I use extension in repository with submodules. The extension creates messages for the submodule even if I click on the pencil next to the desired repository.

<details>
  <summary>Proof of wrong behavior</summary>

  ![image](https://user-images.githubusercontent.com/322910/129557233-e82e4d91-457e-438e-96f1-3fc3e73aa8e1.png)
</details>

If I turn off displaying all repositories except the main repository, the extension still creates a message for the submodule.

<details>
  <summary>How to disable display other repos</summary>

![image](https://user-images.githubusercontent.com/322910/129558912-228cf35c-3d0d-4b9e-b9d5-4873a3da2963.png)
</details>

And there is no way to change the repository. Couldn't find a way to select the repository from #6 

Version v0.18.3

**Comment by bendera** [comment]
Hi,

This behavior is a bit confusing and I can't change it because it depends on the VSCode. When you click on the pencil icon, the repo won't be selected yet. You have to click on the source control input box to select that repository, or you can choose from the "Source Control Repositories" view (if the view is enabled). Whichever option you choose, the "Selected repository:" label will always show the repository name which is actually selected.
