### ISSUE TITLE
When the repository has submodules, Selected repository is sometimes incorrect.

### ISSUE THREAD

**Issue by gtianw** [bendera/vscode-commit-message-editor#68]
As shown below:
![image](https://user-images.githubusercontent.com/91190888/184783964-b9588cc3-bdfc-46c6-93ab-62f843ae95b8.png)
![image](https://user-images.githubusercontent.com/91190888/184784262-1bf5ca72-926b-4cb8-8925-255608ea37d3.png)

**Comment by gtianw** [comment]
Even if I click on the source control input box, or choose from the "Source Control Repositories" view, the problem remains.

**Comment by singularitti** [comment]
This happens to me, too! It always selects the submodule even if I click the button on the main repo. I cannot change it!

**Comment by bendera** [comment]
I've found the root cause of this error, so I'm on it.

**Comment by bendera** [comment]
It's published. Let me know if you still experience this error.

**Comment by singularitti** [comment]
I tried the new version, and the same issue still seems to happen.

**Comment by bendera** [comment]
I tried with this repo but I couldn't reproduce it.
https://github.com/bendera/test-with-submodules

Is your project open source? Can you share it?

**Comment by singularitti** [comment]
I guess the problem should be restated as follows: Clicking the "pencil" icon does not work as expected.
For example, If I put my cursor in the input box of the submodule (in this case, `juliaplots.sty`), and click the pencil icon, what I see is the submodule message editor (which is expected):

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/25192197/232343864-bf4e7ceb-c526-46d6-9b2d-13d230879e0d.png">

If I put my cursor in the input box of the main module (in this case, `julia-tufte-beamer`), and click the pencil icon, what I see is the main module message editor (which is expected):

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/25192197/232343950-0011a6f7-d62d-49bf-bea4-69a72f8f84fd.png">

But if I put my cursor in the input box of the main module, and click the pencil icon in the submodule repo, what I see is the main module message editor (which is not expected), and vice versa.

So it is probably is not a bug to you since you know how to use it correctly. But it is quite confusing for users like us: in my opinion, and I should open the message editor in the repo where I click the pencil icon. It should not depend on where my cursor is. Because it is often the case that I click the icon without anything in the input box: I click it because I want to edit the text in a larger input box. Therefore, the pencil icon should have a higher priority than the cursor position.

**Comment by gtianw** [comment]
In my environment, when I put the cursor in the input box of the main module and click the pencil icon, the submodule message editor will be opened.

**Comment by bendera** [comment]
Until now I thought the repository cannot be accessed where the tab opened from. However, as I see the other git extension like GitHistory can distinguish from where it was opened. I studied the source code of GH and found the solution, so I will able to fix it today. But I don't remember if this option is mentioned anywhere in the official documentation.

**Comment by bendera** [comment]
Done.
